replicaCount: 1
name: repo-test-infra-front

image:
  repository: ghcr.io/visiobook-esp/repo-test-infra-nuxt
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30081

istio:
  enabled: true
  injection: true

  destinationRule:
    enabled: true
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 100
        http:
          http1MaxPendingRequests: 100
          http2MaxRequests: 100
          maxRequestsPerConnection: 2
      loadBalancer:
        simple: ROUND_ROBIN
      outlierDetection:
        consecutiveErrors: 5
        interval: 30s
        baseEjectionTime: 30s

  mtls:
    enabled: true
    mode: ISTIO_MUTUAL

nodeSelector: {}
tolerations: []
affinity: {}

podLabels:
  app: repo-test-infra-front
  version: "latest"
  app.kubernetes.io/name: repo-test-infra-front
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/component: backend

resources: {}

# External secret name - managed by infra repo
# The secret must contain: DATABASE_URL, RSA_PRIVATE_KEY
existingSecret: ""
revisionHistoryLimit: 3 # nombre de revision garder sur un pod
progressDeadlineSeconds: 60 # temps max pour que le pod soit opérationnel avant de considérer que le déploiement a échoué
env:
  SERVICE_NAME: repo-test-infra-front
  # PORT: "3000"
  TRUC: "bidule"
  MARCHIN: "machin"
  